// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdmuutudojadvtlhkcsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkbXV1dHVkb2phZHZ0bGhrY3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyODM0MTYsImV4cCI6MjA2Nzg1OTQxNn0.dTPoH00teUehAdCWyFQeOoUAw_ewuhnxAurhUreJqsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});